### ISSUE TITLE
Can't add the repo

### ISSUE THREAD

**Issue by MaSven** [reitzig/sdkman-for-fish#33] opened 2020-05-04 21:11 UTC
Fish version: 3.1.0
Fisher version: fisher version 3.2.10 ~/.config/fish/functions/fisher.fish

I tried to add the repo but it failes everytime with the following message:

> fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
mv: das angegebene Ziel '/home/sven/.cache/fisher/github.com/reitzig/sdkman-for-fish' ist kein Verzeichnis
cp: der Aufruf von stat für '/home/sven/.cache/fisher/github.com/reitzig/sdkman-for-fish' ist nicht möglich: No such file or directory
done in 0.70s

```
❰sven❙~❱✔≻ fisher
fisher: nothing to commit -- try adding some packages
```
```
❰sven❙~❱✔≻ cat .config/fish/fishfile

```
I ran
```fish
❰sven❙~❱✔≻ fisher add reitzig/sdkman-for-fish
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
mv: das angegebene Ziel '/home/sven/.cache/fisher/github.com/reitzig/sdkman-for-fish' ist kein Verzeichnis
cp: der Aufruf von stat für '/home/sven/.cache/fisher/github.com/reitzig/sdkman-for-fish' ist nicht möglich: No such file or directory
done in 0.70s
```

**Comment by MaSven** [comment] 2020-05-04 21:16
Probably the same as #32

**Comment by MaSven** [comment] 2020-05-04 21:17
Also created an issue in fisher maybe

**Comment by reitzig** [comment] 2020-05-04 22:48
Not sure what to tell you. :/ Seems to be a fisher issue; no code I wrote is actually being run there.

Closing as there seem to be an upstream issue: https://github.com/jorgebucaran/fisher/issues/557

**Closed by reitzig** 2020-05-04 22:48 UTC

**Comment by jorgebucaran** [comment] 2020-05-22 16:49
> Not sure what to tell you. :/ Seems to be a fisher issue; no code I wrote is actually being run there.


Well, not exactly, [this code runs](https://github.com/reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish) for example. Could there be an issue in there?

**Comment by reitzig** [comment] 2020-05-22 17:07
@jorgebucaran Far as I can tell, it doesn't get that far. The message posted by @MaSven mentions `mv` and `cp`, neither of which appears in the file you link.

I for one can't reproduce, either, sooo.... :shrug:

**Comment by jorgebucaran** [comment] 2020-05-22 17:17
@reitzig Gotcha! 👍
